version: '3.7'
services: 
    app:
        container_name: app
        build:
            context: ./backend
            dockerfile: Dockerfile
        image: musicappdb:1.0
        environment: 
            FLASK_ENV: ${FLASK_ENV}
            MONGO_DATABASE: ${MONGO_DATABASE}
            MONGO_ADMIN_USER: ${MONGO_ADMIN_USER}
            MONGO_ADMIN_PWD: ${MONGO_ADMIN_PWD}
            MONGO_HOSTNAME: ${MONGO_HOSTNAME}
        volumes:
            - ./backend/src:/usr/src/backend/src
        ports:
            - 5000:80
        depends_on: 
            - mongodb
    mongodb:
        image: mongo:latest
        container_name: mongodb
        restart: unless-stopped
        command: mongod --auth
        environment: 
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_ADMIN_USER}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ADMIN_PWD}
            MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
        ports:
            - '27017-27019:27017-27019'
        volumes:
            - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
            - ./mongo-volume:/data/db
#         networks:
#             - backend
# networks:
#     backend:
#         driver: bridge
# volumes:
#     mongodbdata:
#         driver: local

