

MSG_PROCESSING = 'Processing'
MSG_RECORD = 'Recoding...'
MSG_SUCCESS = 'Record Success'
MSG_REG_SUCCESS = 'Create file Success'
MSG_FAIL = 'Record Failed'
MSG_SERVICE_UNAVAILABLE = 'Service Unavailable'

CODE_DONE = 1000
CODE_PROCESSING = 1001
CODE_URL_UNAVAILABLE = 1002
CODE_SERVICE_UNAVAILABLE = 1003
CODE_NAME_NOT_EXIST = 1004
CODE_ACCOUNT_NOT_EXIST = 1005
CODE_FILE_EXIST = 1006
CODE_PLAYLIST_NOT_EXIST = 1007
CODE_FAIL = 1008

#voice authenication infor
CHANNELS = 2
RATE = 44100
CHUNK = 1024
RECORD_SECONDS = 3



# User Voice Folder
USER_DIR = "../static/user_voice"