/// Flutter icons IconCustom
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  IconCustom
///      fonts:
///       - asset: fonts/IconCustom.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class IconCustom {
  IconCustom._();

  static const _kFontFam = 'IconCustom';
  static const _kFontPkg = null;

  static const IconData settings_1 = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData album_1 = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData playlist = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData repeat = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shuffle = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mymusic = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
